"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables (with fallback if decouple not installed)
try:
    from decouple import config, Csv
except ImportError:
    # Fallback: read from environment variables if decouple not installed
    import os
    
    class Csv:
        """Fallback Csv class for splitting comma-separated values"""
        def __init__(self, value):
            self.value = value
        
        def __call__(self, x):
            if isinstance(x, str):
                return [item.strip() for item in x.split(',')]
            return x
    
    def config(key, default=None, cast=None):
        """Fallback config function to read environment variables"""
        value = os.getenv(key)  # Don't use default here yet
        if value is None:
            return default  # Return the default directly if env var doesn't exist
        if cast:
            if cast == bool:
                # Convert string to boolean
                return str(value).lower() in ('true', '1', 'yes', 'on')
            elif cast == Csv or (hasattr(cast, '__name__') and 'Csv' in str(cast)):
                return [item.strip() for item in str(value).split(',')]
            elif callable(cast):
                return cast(value)
        return value

DEFAULT_INSECURE_SECRET_KEY = 'django-insecure-change-me-in-production'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default=DEFAULT_INSECURE_SECRET_KEY)

def parse_bool(value):
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() in ('1', 'true', 'yes', 'on', 'dev', 'development')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=parse_bool)

if not DEBUG and SECRET_KEY == DEFAULT_INSECURE_SECRET_KEY:
    raise RuntimeError('SECRET_KEY must be set in production.')

CORS_ALLOWED_ORIGINS = [
    'http://localhost:8000',
    'http://172.104.60.39:8000',
    "https://duladoc.com",
    "https://www.duladoc.com",
]

def parse_allowed_hosts(value):
    if isinstance(value, (list, tuple)):
        return list(value)
    if isinstance(value, str):
        if not value:
            return ['localhost', '127.0.0.1', 'duladoc.com', 'www.duladoc.com']
        return [item.strip() for item in value.split(',')]
    return ['localhost', '127.0.0.1', 'duladoc.com', 'www.duladoc.com']

ALLOWED_HOSTS = [
    "duladoc.com",
    "www.duladoc.com",
    "localhost",
    "127.0.0.1",
    "backend",
]


# Application definition

INSTALLED_APPS = [
    'admin_interface',
    'colorfield',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sitemaps',
    'authentication',
    'ckeditor',
    'ckeditor_uploader',
    'wallet',
    'documents.apps.DocumentsConfig',  # <-- keep this
    'category',
    'django_ses',
    
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'main.urls'
LOGIN_URL = '/auth/login/'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'wallet.context_processors.categories_processor',
                'main.context_processors.seo_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB'),
        'USER': os.getenv('POSTGRES_USER'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
        'HOST': os.getenv('POSTGRES_HOST', 'db'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    }
}


# Password validation


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


TIME_ZONE = 'Asia/Vientiane'
USE_L10N = True

# CKEditor config
CKEDITOR_UPLOAD_PATH = 'uploads/ckeditor/'
CKEDITOR_IMAGE_BACKEND = 'pillow'  # pip install Pillow

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': '100%',
    },
}
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [BASE_DIR / 'main/static']


# Media settings
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=not DEBUG, cast=parse_bool)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=not DEBUG, cast=parse_bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=not DEBUG, cast=parse_bool)
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=0 if DEBUG else 31536000, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=not DEBUG, cast=parse_bool)
SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=False, cast=parse_bool)
SECURE_CONTENT_TYPE_NOSNIFF = True


# Cache Configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'duladoc-cache',
        'TIMEOUT': 3600,  # 1 hour default timeout
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}

# ทดสอบด้วย Gmail
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
# EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
# EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=parse_bool)
# EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
# EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
# DEFAULT_FROM_EMAIL = f'Duladoc <{EMAIL_HOST_USER}>'
# EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=parse_bool) 



# Replace the SES block with:
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp-relay.brevo.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=parse_bool)
EMAIL_HOST_USER = config('BREVO_SMTP_LOGIN', default='')
EMAIL_HOST_PASSWORD = config('BREVO_SMTP_KEY', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='a5a71d001@smtp-brevo.com')

# Amazon SES
# EMAIL_BACKEND = config('EMAIL_BACKEND', default='django_ses.SESBackend')
# AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID', default='')
# AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY', default='')
# AWS_SES_REGION_NAME = config('AWS_SES_REGION_NAME', default='ap-southeast-1')
# AWS_SES_REGION_ENDPOINT = f'email.{AWS_SES_REGION_NAME}.amazonaws.com'
# DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@duladoc.com')
SITE_URL = config('SITE_URL', default='https://duladoc.com')

# ========== SEO Configuration ==========
SITE_ID = 1
SITE_NAME = 'Duladoc'
SITE_DOMAIN = config('SITE_DOMAIN', default='duladoc.com')

# Meta tags default configuration
META_SITE_PROTOCOL = config('META_SITE_PROTOCOL', default='https')

# Sitemap configuration
SITEMAPS_DIR = os.path.join(BASE_DIR, 'static', 'sitemaps')
if not os.path.exists(SITEMAPS_DIR):
    os.makedirs(SITEMAPS_DIR, exist_ok=True)


CSRF_TRUSTED_ORIGINS = [
    "https://duladoc.com",
    "https://www.duladoc.com",
]


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'