# Generated by Django 6.0.1 on 2026-04-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_show_category',
            field=models.BooleanField(default=False),
        ),
    ]
