# Generated by Django 6.0.1 on 2026-05-29 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_add_category_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='category',
            new_name='category_ca_parent__aef57c_idx',
            old_name='category_ca_parent_show_idx',
        ),
    ]
