# Generated by Django 6.0.1 on 2026-03-23 08:25

import ckeditor_uploader.fields
import django.core.validators
import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('subtitle2', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='banners/')),
                ('button_text', models.CharField(default='Learn More', max_length=100)),
                ('button_link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryJobDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=100, verbose_name='ຂໍ້ຄວາມສັ້ນ (Trade-in offer)')),
                ('title', models.CharField(max_length=150, verbose_name='ຫົວຂໍ້ (Supper value deals)')),
                ('highlight_title', models.CharField(max_length=150, verbose_name='ຫົວຂໍ້ເນັ້ນ (On all products)')),
                ('description', models.TextField(verbose_name='ລາຍລະອຽດ')),
                ('button_text', models.CharField(default='ຊື້ເລີຍ', max_length=50, verbose_name='ຂໍ້ຄວາມປຸ່ມ')),
                ('button_link', models.URLField(verbose_name='ລິ້ງປຸ່ມ')),
                ('image', models.ImageField(upload_to='hero_slider/', verbose_name='ຮູບ Slider')),
                ('is_active', models.BooleanField(default=True, verbose_name='ເປີດໃຊ້')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Slider',
                'verbose_name_plural': 'Hero Sliders',
            },
        ),
        migrations.CreateModel(
            name='NewsFlash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link_text', models.CharField(blank=True, max_length=100, null=True)),
                ('link_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmallBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle_one', models.CharField(blank=True, max_length=200)),
                ('subtitle_two', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='small_banners/')),
                ('button_text', models.CharField(default='Shop Now', max_length=100)),
                ('button_link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'txt', 'pptx', 'pot', 'potx', 'xls', 'xlsx', 'pps', 'ppsx']), documents.models.validate_file_size])),
                ('pages', models.IntegerField(default=0)),
                ('preview_file', models.FileField(blank=True, null=True, upload_to='previews/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='preview_images/%Y/%m/%d/')),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='attached_files/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar'])])),
                ('name_attached_file', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured_book', models.BooleanField(default=False)),
                ('is_popular_book', models.BooleanField(default=False)),
                ('is_new_book', models.BooleanField(default=False)),
                ('preview_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('downloads', models.IntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='category.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('full_time', 'ວຽກເຕັມເວລາ'), ('part_time', 'ວຽກພາດທາມ'), ('freelance', 'ວຽກສັນຍາຈ້າງ')], max_length=20)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('contact_info', models.CharField(max_length=255)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('status', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
