# Generated by Django 6.0.1 on 2026-04-01 02:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='seller_revenue_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.80'), help_text='สัดส่วนที่เจ้าของเอกสารได้รับ เช่น 0.80 = 80%', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))]),
        ),
        migrations.AlterField(
            model_name='document',
            name='downloads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
