# Generated by Django 6.0.1 on 2026-05-20 09:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_seller_revenue_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='seller_revenue_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.80'), help_text='ສ່ວນທີ່ເຈົ້າຂອງເອກກະສານຈະໄດ້ຮັບເຊັ່ນ 0.80 = 80%', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))]),
        ),
    ]
