# Generated by Django 6.0.1 on 2026-05-29 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_add_indexes_and_select_related'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_d_is_acti_bba6b9_idx',
            old_name='documents_d_is_activ_created_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_d_is_feat_bfd10f_idx',
            old_name='documents_d_is_feat_is_activ_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_d_is_popu_0cb448_idx',
            old_name='documents_d_is_pop_is_activ_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_d_is_new__6b5cd0_idx',
            old_name='documents_d_is_new_is_activ_idx',
        ),
    ]
