# Generated by Django 6.0.1 on 2026-04-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topuprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'ລໍຖ້າກວດສອບ'), ('approved', 'ອະນຸມັດ'), ('rejected', 'ປະຕິເສດ')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('topup', 'ຕື່ມເງິນ'), ('purchase', 'ຊື້ເອກະສານ')], max_length=20),
        ),
    ]
