# Generated by Django 6.0.1 on 2026-04-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_topuprequest_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_banks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_banks', models.CharField(max_length=255)),
                ('name_account', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.IntegerField(blank=True, null=True)),
                ('image_qrccode', models.ImageField(upload_to='wallet/qr_code/%Y/%m/')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='platform_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchase',
            name='seller_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
