# Generated by Django 6.0.1 on 2026-04-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_payment_banks_purchase_platform_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_banks',
            name='account_number',
            field=models.CharField(blank=True, null=True),
        ),
    ]
