# Generated by Django 6.0.1 on 2026-04-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_payment_banks_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_banks',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
