# Generated by Django 6.0.1 on 2026-04-06 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_payment_banks_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('topup', 'ຕື່ມເງິນ'), ('purchase', 'ຊື້ເອກະສານ'), ('revenue', 'ລາຍໄດ້ຈາກການຂາຍ'), ('platform_fee', 'ຄ່າທຳນຽມລະບົບ'), ('withdraw', 'ຖອນເງິນ')], max_length=20),
        ),
        migrations.CreateModel(
            name='WithdrawRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'ລໍຖ້າດຳເນີນການ'), ('approved', 'ອະນຸມັດແລ້ວ'), ('rejected', 'ປະຕິເສດ')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('slip_image', models.ImageField(blank=True, null=True, upload_to='withdraw_slips/%Y/%m/')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
