# Generated by Django 6.0.1 on 2026-05-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_alter_purchase_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
    ]
