# Generated by Django 6.0.1 on 2026-05-22 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_purchase_download_count'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchase',
            name='unique_user_document_purchase',
        ),
    ]
