# Generated by Django 6.0.1 on 2026-05-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_remove_purchase_unique_user_document_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawrequest',
            name='qrcode_image',
            field=models.ImageField(blank=True, help_text='ອັບໂຫລດ QR Code ຂອງບັນຊີທະນາຄານທີ່ຈະຮັບເງິນ', null=True, upload_to='withdraw_qrcodes/%Y/%m/', verbose_name='QR Code ບັນຊີທະນາຄານ'),
        ),
    ]
