# Generated by Django 6.0.1 on 2026-05-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_withdrawrequest_qrcode_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='image_qrcode',
            field=models.ImageField(blank=True, upload_to='wallet/qr_codeuser_withdraw/%Y/%m/'),
        ),
    ]
