# Generated by Django 6.0.1 on 2026-05-29 04:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_payment_banks_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_banks',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment_banks',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
