# Generated by Django 6.0.1 on 2026-05-31 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_payment_banks_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_banks',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment_banks',
            name='name_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
